###
//crear critica
POST http://localhost:5000/api/critMovies  HTTP/1.1
Content-Type: application/json

{
    "name": "Wilson argote",
    "peliculaFav":"El rey leon",
    "puntuacion": "⭐⭐⭐⭐"
}

###
//ver todas las criticas.
GET http://localhost:5000/api/critMovies  HTTP/1.1

###
//Buscar una critica especifica
GET http://localhost:5000/api/critMovies/63eceb1ae4546109e942f54b  HTTP/1.1


###
//Editar critica
PUT  http://localhost:5000/api/critMovies/63eceb1ae4546109e942f54b HTTP/1.1
Content-Type: application/json

{
    "name": "Miguel",
    "peliculaFav":"Eterno resplandor de una mente sin recuerdo",
    "puntuacion": "⭐⭐⭐⭐"
}

###
//Eliminar una critica
DELETE http://localhost:5000/api/critMovies/63ececc11aac4daa714c4da3 HTTP/1.1
